version: "3"
services:
  web:
    build: .
    container_name: currency-converter
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ".:/usr/src/app"
      # - "/usr/src/app/node_modules"
