name: Upload Image to DockerHub

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build --tag currency-converter:latest .

    - name: Run Docker container
      run: docker run -d --name mycontainer currency-converter:latest

    - name: Push Docker image to DockerHub
      run: docker push ${{DOCKER_USERNAME}}/currency-converter:latest
