name: upload image
on:
  push: 
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/currency-converter:latest

      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USER }}/currency-converter:latest
