name: PR Test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build --build-arg API_KEY=$API_KEY --tag currency-converter:latest .
    
    - name: Run Docker container
      run: |
        docker run -e API_KEY=$API_KEY -d --name mycontainer currency-converter:latest
        echo "::set-output name=container_id::$(docker inspect --format='{{.Id}}' mycontainer)"

    - name: Wait for container to start
      run: sleep 10  

    - name: Get container IP address
      run: |
        container_id=$(echo "${{ steps.run_container.outputs.container_id }}")
        container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
        echo "Container IP Address: $container_ip"
    
    - name: Debug container logs
      run: docker logs mycontainer
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.9'
    
    - name: Install software
      run: sudo apt-get install -y
    
    - name: Install the necessary packages
      run: pip install requests webdriver-manager selenium pytest
       
    - name: Run the PytTest script
      run: pytest -rA
