name: PR Test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # - name: Build Docker image
    #   run: docker build --build-arg API_KEY=$API_KEY --tag currency-converter:latest .
    
    # - name: Run Docker container
    #   run: |
    #     docker run -e API_KEY=$API_KEY -d --name mycontainer -p 80:80 currency-converter:latest

    - name: Run Docker container
      run: |
        docker-compose up -d
      env:
          API_KEY: ${{ secrets.API_KEY }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.9'
    
    - name: Install software
      run: sudo apt-get install -y
    
    - name: Install the necessary packages
      run: pip install requests webdriver-manager selenium pytest
       
    - name: Run the PytTest script
      run: pytest -rA
